/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComalSarabjotIndexRouteImport } from './routes/comal-sarabjot/index'
import { Route as ComalSarabjot1213RouteImport } from './routes/comal-sarabjot/12-13'
import { Route as ComalSarabjot13RouteImport } from './routes/comal-sarabjot/13'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComalSarabjotIndexRoute = ComalSarabjotIndexRouteImport.update({
  id: '/comal-sarabjot/',
  path: '/comal-sarabjot/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComalSarabjot1213Route = ComalSarabjot1213RouteImport.update({
  id: '/comal-sarabjot/12-13',
  path: '/comal-sarabjot/12-13',
  getParentRoute: () => rootRouteImport,
} as any)
const ComalSarabjot13Route = ComalSarabjot13RouteImport.update({
  id: '/comal-sarabjot/13',
  path: '/comal-sarabjot/13',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comal-sarabjot/12-13': typeof ComalSarabjot1213Route
  '/comal-sarabjot/13': typeof ComalSarabjot13Route
  '/comal-sarabjot/': typeof ComalSarabjotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comal-sarabjot/12-13': typeof ComalSarabjot1213Route
  '/comal-sarabjot/13': typeof ComalSarabjot13Route
  '/comal-sarabjot': typeof ComalSarabjotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comal-sarabjot/12-13': typeof ComalSarabjot1213Route
  '/comal-sarabjot/13': typeof ComalSarabjot13Route
  '/comal-sarabjot/': typeof ComalSarabjotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/comal-sarabjot/12-13' | '/comal-sarabjot/13' | '/comal-sarabjot/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comal-sarabjot/12-13' | '/comal-sarabjot/13' | '/comal-sarabjot'
  id:
    | '__root__'
    | '/'
    | '/comal-sarabjot/12-13'
    | '/comal-sarabjot/13'
    | '/comal-sarabjot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComalSarabjot1213Route: typeof ComalSarabjot1213Route
  ComalSarabjot13Route: typeof ComalSarabjot13Route
  ComalSarabjotIndexRoute: typeof ComalSarabjotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comal-sarabjot/': {
      id: '/comal-sarabjot/'
      path: '/comal-sarabjot'
      fullPath: '/comal-sarabjot/'
      preLoaderRoute: typeof ComalSarabjotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comal-sarabjot/12-13': {
      id: '/comal-sarabjot/12-13'
      path: '/comal-sarabjot/12-13'
      fullPath: '/comal-sarabjot/12-13'
      preLoaderRoute: typeof ComalSarabjot1213RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comal-sarabjot/13': {
      id: '/comal-sarabjot/13'
      path: '/comal-sarabjot/13'
      fullPath: '/comal-sarabjot/13'
      preLoaderRoute: typeof ComalSarabjot13RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComalSarabjot1213Route: ComalSarabjot1213Route,
  ComalSarabjot13Route: ComalSarabjot13Route,
  ComalSarabjotIndexRoute: ComalSarabjotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
